collection_order:
  - script 1.js
  - script3.js
  - script5.js
  - script10.js
allowed_scripts:
  - script2.js
  - script3.js
  - script5.js
layers:
  - poststand-core-layer-v1
timeoutDurationInSecs: 900
memorySize: null
ephemeralStorageSize: null
retryAttempts: 0
userLocalSecrets: false
secrets:
  - secretTwo
