scripts:
  - script0.js
  - script1.js
  - script11.js
  # - script4.js
  #- script2.js
  - script3.js
  # - script4.js
layers:
  - poststand-core-layer-v1
timeoutDurationInSecs: 900
memorySize:
ephemeralStorageSize:
retryAttempts: 0
userLocalSecrets: false #this is ignored when running in AWS Lambda
secrets:
  - secretOne
  - secretTwo
