collection_order:
  - script 1.js
  # - script4.js
  #- script2.js
  - script3.js
  # - script4.js
  - script5.js
allowed_scripts:
  - script 1.js
  - script2.js
  - script3.js
  - script5.js
  - script10.js
includeNodeModules: false     # <-- NEW — set to false or omit to rely on the layer
layers:
  - poststand-core-layer-v7
handlerFile: handler_v8.js
timeoutDurationInSecs: 900
memorySize: 2048
ephemeralStorageSize: 2048
retryAttempts: 0
userLocalSecrets: false #this is ignored when running in AWS Lambda
secrets:
  - secretOne
  - secretTwo
